// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptTi5Bgd_oPrvwpG4_EYJvG-A7BE6cZc',
    appId: '1:818737747367:web:4e2b002605426d5e3d1282',
    messagingSenderId: '818737747367',
    projectId: 'apexfirebase-34fa1',
    authDomain: 'apexfirebase-34fa1.firebaseapp.com',
    storageBucket: 'apexfirebase-34fa1.firebasestorage.app',
    measurementId: 'G-DTS62L1S5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4v1oz8gmDHz8a9FYaZPqBsSBUZ4EoC6I',
    appId: '1:818737747367:android:58df8442439966b13d1282',
    messagingSenderId: '818737747367',
    projectId: 'apexfirebase-34fa1',
    storageBucket: 'apexfirebase-34fa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6P3YgXqXg61THnCoaaWovPKyMNQFqNs',
    appId: '1:818737747367:ios:5672463e27cce17b3d1282',
    messagingSenderId: '818737747367',
    projectId: 'apexfirebase-34fa1',
    storageBucket: 'apexfirebase-34fa1.firebasestorage.app',
    iosBundleId: 'com.example.apex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6P3YgXqXg61THnCoaaWovPKyMNQFqNs',
    appId: '1:818737747367:ios:5672463e27cce17b3d1282',
    messagingSenderId: '818737747367',
    projectId: 'apexfirebase-34fa1',
    storageBucket: 'apexfirebase-34fa1.firebasestorage.app',
    iosBundleId: 'com.example.apex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAptTi5Bgd_oPrvwpG4_EYJvG-A7BE6cZc',
    appId: '1:818737747367:web:27e0a0aa12b0f5dd3d1282',
    messagingSenderId: '818737747367',
    projectId: 'apexfirebase-34fa1',
    authDomain: 'apexfirebase-34fa1.firebaseapp.com',
    storageBucket: 'apexfirebase-34fa1.firebasestorage.app',
    measurementId: 'G-1XN90DH6E6',
  );
}
